# -*- coding: utf-8 -*-
"""Mercado Inmobiliario en CABA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cWlwUiTVMpbFOWdPohLVKxppk8fZwWjo
"""

import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

pip freeze

precio_alq = pd.read_csv('/content/drive/MyDrive/DATOS/GCBA/Vivienda/precio-alquiler-deptos.csv')
precio_vta = pd.read_csv('/content/drive/MyDrive/DATOS/GCBA/Vivienda/precio-venta-deptos.csv')

precio_alq.head(2)

precio_alq.info()

precio_vta.head(2)

# len(precio_alq.barrio.unique()) == len(precio_vta.barrio.unique())  TENGO LA MISMA CANTIDAD DE BARRIOS

## TENGO MAS AÑOS EN UN DF QUE EN OTRO // DEBERIA CONSIDERAR FILTRAR EL DF DE VENTAS PARA QUEDARME CON LOS DATOS DE LOS AÑOS DEL DF DE ALQUILERES

precio_alq.anio.unique()

precio_vta.año.unique()

a = precio_alq.groupby(['barrio','anio', 'ambientes'], as_index=False)['precio_prom'].mean().sort_values('precio_prom', ascending=False)
a= a.reset_index(drop=True)
a.head()

a.info()  ## TENGO UN MONTON DE VALORES NULOS

pd.options.display.float_format = '{:.2f}'.format

b = a.loc[(a.precio_prom >=0),:].sort_values(by='precio_prom',ascending=True)   ## ACA TENGO FILTRADO POR AÑO Y SIN VALORES NULOS 
b = b.reset_index(drop=True)
b = b.rename(columns={'anio':'año'})  ## ASI CAMBIO EL NOMBRE DE LA COLUMNA
b.head()

fig1 = px.bar(data_frame = b,
            x = b['barrio'],
            y = b['precio_prom'],
            color = b['año'],
            title = 'Precio promedio de alquileres en CABA por Barrio - Años 2013 a 2019',
            labels = {'precio_prom' : 'Precio Promedio' , 'barrio' : 'Barrio'}
        )
fig1.update_layout(
    showlegend = False,
    title = {"x":0.5,#centrar
             "y":0.9,#bajar
             "font":{"size":30, "color": "blue"}
             }  
)
plt.show()
fig1

plt.figure(figsize=(21,12))
fig3 = sns.boxplot(data = b,
               y = b['barrio'],
               x = b['precio_prom'],
               orient = 'h',
               fliersize = 3 ,
               width = 0.6)
            
fig3 = sns.stripplot(data = b,
               y = b['barrio'],
               x = b['precio_prom'],
              color="yellow", 
              jitter=0.3, 
              size=3)
fig3.set_title("Boxplot Precio promedio de alquileres por Barrio") #titulo
fig3.set_xlabel('Precios promedio') #nombre del eje x
fig3.set_ylabel('Barrios') #nombre del eje y

plt.show()

b.ambientes.unique()

b['ambientes'] = b['ambientes'].replace(
    {'2 ambientes': "2", 
     '3 ambientes': "3"})

b['ambientes'].astype(str).astype(int)

(
  b  
  .groupby(['ambientes','barrio','año'],as_index=False)    ## NO ME SIRVE CALCULAR MINIMOS Y MAXIMOS PORQUE SOLO TENGO EL PRECIO PROMEDIO
  .agg({'precio_prom':['max','min']})
)

e = b.loc[(b['año'].isin([2018,2019])) ,:]
e.head(2)

fig4 = px.bar(data_frame= e,
            x = e['barrio'],
            y = e['precio_prom'],
            color = e['ambientes'],           
            title = 'Precio promedio de alquileres en CABA por cantidad de Ambientes - Años 2018 y 2019',
            labels = {'y' : 'Precio Promedio' , 'x' : 'Barrio'},
            orientation = 'v'            
        )
fig4.update_layout(
    showlegend = False,
    title = {"x":0.5,#centrar
             "y":0.9,#bajar
             "font":{"size":30, "color": "blue"}
             }  
)
plt.show()
fig4

fig=px.bar(data_frame = e, x= 'barrio', y='precio_prom', color='ambientes', text='año')
fig.update_traces(texttemplate='%{text:0.2s}',textposition='outside')
fig.show()

c = precio_alq.groupby(['comuna','anio'], as_index=False)['precio_prom'].mean().sort_values('precio_prom', ascending=False)
c= c.loc[(c.precio_prom >=0),:].sort_values(by='precio_prom',ascending=True)   ## ACA TENGO FILTRADO POR AÑO Y SIN VALORES NULOS 
c = c.reset_index(drop=True)
c = c.rename(columns={'anio':'año'})  ## ASI CAMBIO EL NOMBRE DE LA COLUMNA
c

d = c.loc[(c['año'] .isin ([2018,2019])),:].sort_values(by='comuna',ascending=False)
d.reset_index(drop=True)
d.head()

d.loc[d.comuna == 8]

fig2 = px.bar(data_frame= d,
                  x = d['comuna'],
                  y = d['precio_prom'],
                  color = d['año'], 
                  title = 'Precio promedio de alquileres en CABA por Comuna - Años 2018 y 2019',
                  labels = {'precio_prom' : 'Precio Promedio' , 'comuna' : 'Comuna'}
                  )
fig2.update_layout(
    showlegend = False,
    title = {"x":0.5,#centrar
             "y":0.9,#bajar
             "font":{"size":30, "color": "blue"}
             }  
)
fig2

# Commented out IPython magic to ensure Python compatibility.
# %whos
